name: smartannotation

dependencies:
  - python>=3.7
  - pip
  - cudnn
  - cudatoolkit>=10.1
  - pip:
    - tensorflow==2.7.0
    - opencv-python
    - opencv-contrib-python
    - lxml
    - tqdm
    - fastapi
    - uvicorn
    - h5py==2.10.0
    - imgaug==0.4.0
    - ipython==7.31.0
    - keras==2.7.0
    - matplotlib==3.3.4
    - numpy==1.19.5
    - pycocotools==2.0.3
    - scikit_image==0.18.1
    - scipy==1.6.2
    - skimage==0.0
    - -e .
