name: smartannotation

dependencies:
  - python>=3.7
  - pip
  - cudnn
  - cudatoolkit>=10.1
  - shapely
  - pip:
    - tensorflow
    - opencv-python
    - opencv-contrib-python
    - lxml
    - tqdm
    - fastapi
    - uvicorn
    - h5py
    - imgaug
    - ipython
    - keras
    - matplotlib
    - numpy
    - scikit_image
    - scipy
    - scikit-image
    - shapely
    - Jinja2
    - -e .
